# Generated by Django 5.0.2 on 2024-08-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Blog', '0002_alter_blog_blog_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_content',
            field=models.TextField(verbose_name='What is on your mind ?'),
        ),
    ]
